---
title: "Happiness Investigation"
output: html_notebook
---

```{r Reading in the CSV file}
file <- 'happiness_years.csv'
happiness <- read.csv(file)

happiness
```

```{r Filtering Groups for Paired Samples T-Test}
library ("dplyr")
# filtering data for pre-covid years (2018-2019)
pre_covid = filtered_happy <- filter(happiness, Year %in% c(2018,2019))
pre_covid

# filtering data for during/post-covid years (2020-2021)
post_covid = filtered_happy <- filter(happiness, Year %in% c(2020,2021))
post_covid 
```

```{r Descriptive Statistics Pre-COVID}
max(pre_covid$Happiness)
min(pre_covid$Happiness)
mean(pre_covid$Happiness)
median(pre_covid$Happiness)
sd(pre_covid$Happiness)
```

```{r Descriptive Statistics Post-COVID}
max(post_covid$Happiness)
min(post_covid$Happiness)
mean(post_covid$Happiness)
median(post_covid$Happiness)
sd(post_covid$Happiness)
```

```{r Testing Assumptions for T-Test: Normal Distribution}
# generating a histogram
hist(filtered_happy$Happiness, xlab = "Happiness", col = "yellow", border = "black")

# empirical test of normality (Shapiro-Wilk)
shapiro.test(filtered_happy$Happiness)
```


```{r Wilcoxon Signed Rank Test since normality assumption was violated}
# this method does not assume a normal distribution
wilcox.test(pre_covid$Happiness, post_covid$Happiness, paired = TRUE)

```

```{r Checking Assumptions for a Multiple Regression: Linear Relationship}
#Happiness versus GDP
plot(x = filtered_happy$GDP.per.Capita,y = filtered_happy$Happiness,
     xlab = "GDP per Capita",
     ylab = "Happiness",
     main = "Happiness Versus GDP per Capita",
     pch = 19,
     col = "green")
#Happiness versus Social Support
plot(x = filtered_happy$Social.Support,y = filtered_happy$Happiness,
     xlab = "Social Support",
     ylab = "Happiness",
     main = "Happiness Versus Social Support",
     pch = 19,
     col = "blue")
#Happiness versus Life Expectancy
plot(x = filtered_happy$Life.Expectancy,y = filtered_happy$Happiness,
     xlab = "LIfe Expectancy",
     ylab = "Happiness",
     main = "Happiness Versus Life Expectancy",
     pch = 19,
     col = "red")
#Happiness versus Freedom
plot(x = filtered_happy$Freedom,y = filtered_happy$Happiness,
     xlab = "Freedom",
     ylab = "Happiness",
     main = "Happiness Versus Freedom",
     pch = 19,
     col = "orange")
#Happiness versus Corruption
plot(x = filtered_happy$Corruption,y = filtered_happy$Happiness,
     xlab = "Corruption",
     ylab = "Happiness",
     main = "Happiness Versus Corruption",
     pch = 19,
     col = "brown")
#Happiness versus Generosity
plot(x = filtered_happy$Generosity,y = filtered_happy$Happiness,
     xlab = "Generosity",
     ylab = "Happiness",
     main = "Happiness Versus Generosity",
     pch = 19,
     col = "purple")

```
```{r Pearson's Correlations Between Happiness and Other Factors}
HappyvGDP = cor.test(filtered_happy$Happiness, filtered_happy$GDP.per.Capita, method="pearson")
HappyvSS =  cor.test(filtered_happy$Happiness, filtered_happy$Social.Support, method="pearson")
HappyvLE =  cor.test(filtered_happy$Happiness, filtered_happy$Life.Expectancy, method="pearson")
HappyvF =  cor.test(filtered_happy$Happiness, filtered_happy$Freedom, method="pearson")
HappyvC =  cor.test(filtered_happy$Happiness, filtered_happy$Corruption, method="pearson")
HappyvGen = cor.test(filtered_happy$Happiness, filtered_happy$Generosity, method = "pearson")

HappyvGDP
HappyvSS
HappyvLE
HappyvF
HappyvC
HappyvGen
```

```{r Checking Assumptions for a Multiple Regression: No Multicollinearity}
model <- lm(Happiness ~ GDP.per.Capita + Social.Support + Freedom + Life.Expectancy, data=filtered_happy)
summary(model)
# checking VIF value
#install.packages("car")
library(car)
vif(model)

# visualizing VIF values
vif_values <- vif(model)

# generating a horizontal bar chart to display the VIF value
barplot(vif_values, main = "VIF Values", horiz = TRUE, col = "steelblue")

# add vertical line at 5
abline(v = 5, lwd = 3, lty =2)

# generating correlation matrix for predictor variables
predictors <- filtered_happy[,c("GDP.per.Capita", "Social.Support", "Freedom", "Life.Expectancy")]
cor(predictors, method="pearson")

```

```{r Calculating the Principal Components}
#calculating the principal components
results <- prcomp(filtered_happy[,4:7], scale = TRUE)

#reversing the signs
results$rotation <- -1*results$rotation

#display the principal components
results$rotation

#reverse the signs of the scores
results$x <- -1*results$x

#display the first six scores
head(results$x)

```
```{r Visualizing the Results}
#visualizing the results
biplot(results, scale = 0)

#display the highest happiness values
head(filtered_happy[order(-filtered_happy$Happiness),])
```
```{r Finding the Variance Explained by Each Principal Component}
#calculating the total variance explained by each principal component
results$sdev^2 / sum(results$sdev^2)

#calculate total variance explained by each principal component
var_explained = results$sdev^2 / sum(results$sdev^2)

#create scree plot
#install.packages("ggplot2")
library(ggplot2)
qplot(c(1:4), var_explained) +
  geom_line() +
  xlab("Principal Component") +
  ylab("Vairance Explained") +
  ggtitle("Scree Plot") +
  ylim(0,1)
```


```{r Fitting the PCR Model}
#making the results reproducible
set.seed(42)

#fit the PCR model
#install.packages("pls")
library(pls)
pcr_model <- pcr(Happiness ~ GDP.per.Capita + Social.Support + Freedom + Life.Expectancy, data=filtered_happy, scale = TRUE, validation = "CV")
```
```{r}
#view a summary of model fitting
summary(pcr_model)
```
```{r Visualizing the model fitting}
#visualize cross-validation plots
validationplot(pcr_model)
validationplot(pcr_model, val.type="MSEP")
validationplot(pcr_model, val.type="R2")
```

```{r Using the Final Model to Make Predictions}
# defining the training and resting sets
train <- filtered_happy[1:293, c("Happiness", "GDP.per.Capita", "Social.Support", "Life.Expectancy", "Freedom")]
y_test <- filtered_happy[294:nrow(filtered_happy), c("Happiness")]
test <- filtered_happy[294:nrow(filtered_happy), c("GDP.per.Capita", "Social.Support", "Life.Expectancy", "Freedom")]

# using the model to make predictions on a test set
pcr_model <- pcr(Happiness ~ GDP.per.Capita + Social.Support + Freedom + Life.Expectancy, data=filtered_happy, scale = TRUE, validation = "CV")
pcr_prediction <-predict(pcr_model, test, ncomp=1)

```


```{r Viewing RMSE}
#calculate the RMSE
rmse <- sqrt(mean((pcr_prediction - y_test)^2))
rmse
```

```{r Obtaining Decision Tree}
#install.packages("rpart")
#install.packages("rpart.plot")
library(rpart)
library(rpart.plot)

#generating a decision tree
rpart.model <- rpart(Happiness ~ ., data=train, method="anova")

rpart.plot(rpart.model)
```

```{r Partial Least Squares Approach}
library(pls)
set.seed(53)
train_pls<- 
test_pls <- (!train_pls)
```



